# -*- coding: utf-8 -*-
"""Taller 1 en clase

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvxetuhJu2bchaqDdzbw9gb4DM9cUWNQ

# TALLER 1

pregunta 1 : Escriba un programa que solicite dos números enteros y calcule su división. El programa debe definir si la división es exacta o no. Si no es exacta, debe imprimir cuál es su residuo. ¿Qué debería imprimir el programa si la división es entre cero?
"""

num1 = int(input("Ingresar primer nuumero:  "))
num2 = int(input("Ingresar segundo numero:  "))


def divisible_por_cada_otra(num1, num2):
    if (num1 == 0) or (num2==0):
        print("Error no pone 0")

    elif (num1%num2 == 0 ) or (num2%num1 == 0 ):
        print("Exactamente divisible")
    else:
        print("No Exactamente divisible")
        alta,baja= max(num1,num2),min(num1,num2)
        print("Su remainder es ", alta%baja)

divisible_por_cada_otra(num1, num2)

"""Pregunta 2: Escriba un programa que pida dos números e indique si uno es múltiplo del otro.

"""

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

if a % b == 0:
    print(a, "is divisible by", b)
else:
    print(a, "is not divisible by", b)

"""Pregunta 3:Escriba un programa que ordene, de menor a mayor, las edades de tres hermanos. ¿Qué pasaría si son gemelos? ¿Qué pasaría si son trillizos?"""

edad1=int(input("entre edad1: "))
edad2=int(input("entre edad2: "))
edad3=int(input("entre edad3: "))
if edad1>edad2 and dade1>dade3:
    print("age1 tiene mas edad")
elif edad2>edad1 and edad2>dade3:
    print("age2 tiene mas edad")
else:
    print("age3 tiene mas edad")
if edad1<edad2 and edad1<edad3:
    print("age1 tiene menos edad")
elif edad2<edad1 and edad2<edad3:
    print("age2 tiene menos edad")
else:
     print("age3 tiene menos edad")

"""Pregunta 4: DIAN le ha contratado para identificar si una persona debe pagar impuesto de renta o no. ¿Qué datos debería suministrar? Escriba un programa con su solución.

"""

status = input("Enter you tax status: ")
bIsMarried = status.lower() == "married"
income = int(input("Please enter your annual income: "))
totalTaxes = 0.0

if not bIsMarried:
if income>= 0 and income<=30400:
totalTaxes = 0
elif income > 30400 and income <= 84200:
totalTaxes = income * .12
elif income > 84200 and income <= 160725:
totalTaxes = income * .24
elif income>160725:
totalTaxes=income* .35
else:
if income>= 0 and income<=60800:
totalTaxes = 0
elif income > 60800 and income <= 168400:
totalTaxes = income * .12
elif income > 84200 and income <= 321450:
totalTaxes = income * .24
elif income>321450:
totalTaxes=income* .35

#print("As a "+status)
print(f"Your tax amount is {totalTaxes}")

"""Pregunta 5: Escriba un programa que, de acuerdo al código del estudiante, defina a qué universidad pertenece.

a. Si el código empieza con U y tiene 8 dígitos, pertenece a la UNAB

b. Si los cuatro primeros dígitos es mayor a 1950 , pertenece a la UIS.

c. Si el código empieza con A y tres ceros seguidos, pertenece a los ANDES.

d. 1000 exp. adicional: Si el código de la UNAB termina en 26, debe imprimir que es ingeniero electrónico. Si termina en 32, ingeniero de sistemas. Si termina en 50, pertenece a ingeniería de administración de empresas.

e. 1000 xp. Adicional: Defina códigos con los dos últimos caracteres para la UIS y ANDES, de las mismas carreras.

"""

def university(code):
    if code.startswith("U") and len(code) == 8:
        print("You belong to UNAB.")
        if code.endswith("26"):
            print("You are an electronic engineer.")
        elif code.endswith("32"):
            print("You are a systems engineer.")
        elif code.endswith("50"):
            print("You belong to business administration engineering.")
    elif code.startswith("A") and code[1:4] == "000":
        print("You belong to the ANDES.")
        if code.endswith("26"):
            print("You are an electronic engineer.")
        elif code.endswith("32"):
            print("You are a systems engineer.")
        elif code.endswith("50"):
            print("You belong to business administration engineering.")
    elif int(code[:4]) > 1950:
        print("You belong to the UIS.")
        if code.endswith("26"):
            print("You are an electronic engineer.")
        elif code.endswith("32"):
            print("You are a systems engineer.")
        elif code.endswith("50"):
            print("You belong to business administration engineering.")
    else:
        print("The code does not belong to any university.")

"""pregunta 6: Escriba un programa que le pregunte sus cuatro notas y calcule su promedio actual. Si su promedio es mayor a 4.5, se le diga que está eximido del último examen. Si su nota se encuentra entre 3.5 y 4.5 (intervalo abierto) se le indique que debe presentar el examen. Si la nota se encuentra entre 3 y 3.5 (intervalo abierto), se le indique que adicional al examen, debe presentar un trabajo. Si la nota está entre intervalo abierto entre 2 y 3, decir que debe presentar habilitación. De lo contrario, se le debe indicar al estudiante que perdió la materia irremediablemente.

"""

print("Enter your four grades below")
print("----------------------------")

totalGrades = 0

# for loop to ask user to enter four grades
for n in range(4):
    # read from keyboard
    grades = float(input("Enter grade {}: ".format(n+1)))
    # calculate total grades
    totalGrades += grades

# calculate average grades
avgGrades = totalGrades/4
# display average grades
print("Your current average: {:.2f}".format(avgGrades))

#  If average is greater than 4.5
if avgGrades > 4.5:
    print("You are exempt from the last ex@m.")
# If average is between 3.5 and 4.5
elif 3.5 < avgGrades <= 4.5:
    print("Take the ex@m.")
# If the average is between 3 and 3.5
elif 3.0 < avgGrades <= 3.5:
    print("In addition to the ex@m, you must submit a paper.")
# If the average is between 2 and 3.0
elif 2.0 < avgGrades <= 3.0:
    print("You must present qualification.")
# otherwise
else:
    print("You has irretrievably failed the subject.")

"""Pregunta 7: Escriba un programa que pregunte tu fecha de nacimiento, e indique cuántos días faltan para tu cumpleaños y cuántos años tienes.

"""

from datetime import datetime


name = raw_input("Enter your name : ")


birthdate = raw_input("Enter your date of birth(dd/mm/yyyy): ")


day, month, year = birthdate.split("/")


day, month, year = int(day), int(month), int(year)


today = datetime.now().date()


tyear, tmonth, tday = str(today).split('-')


tyear, tmonth, tday = int(tyear), int(tmonth), int(tday)


age = tyear - year


if tmonth<month:

age=age-1


if tmonth==month:


if tday-day<=30 and tday-day>0:

age=age

else:

age=age-1



print "Your age is ",age



days = (tmonth - month)*30 + (tday - day)


if days >= -2 and days <= 0 :

print "happy birthday!"

"""Pregunta 8:Escriba un programa que defina si un número es bisiesto. (Un año es bisiesto cuando son múltiplos de 4, pero no son múltiplos de 100.

"""

y = int(input("Enter any number: "))
if(y%4 == 0 and y%100 != 0) or (y%400 == 0) :
    print(y, "Yes it is a leap year.")
else :
    print(y, "No it is not a leap year.")

"""Pregunta 9: Escriba un programa que solicite los coeficientes de la ecuación de la recta ax+b=0 y escriba la solución.

"""

a = float(input("Enter a: "))

b = float(input("Enter b: "))

if a == 0:

print("The equation is not linear.")

else:

print("x =", -b/a)

"""Pregunta 10: Escriba un programa que halle la pendiente de la recta ax+b=c.  

"""

x1 = float(input('Enter x1: '))
y1 = float(input('Enter y1: '))
x2 = float(input('Enter x2: '))
y2 = float(input('Enter y2: '))

slope = (y2 - y1) / (x2 - x1)
distance = ((y2-y1)**2 + (x2-x1)**2)**0.5

print('Slope is:', slope)
print('Distance is:', distance)

"""Pregunta 11: Escriba un programa que pida los coeficientes de una ecuación de segundo grado (a x² + b x + c = 0) y escriba la solución.

Se recuerda que una ecuación de segundo grado puede no tener solución, tener una solución única, tener dos soluciones o que todos los números sean solución. Se recuerda que la fórmula de las soluciones cuando hay dos soluciones es x = (-b ± √(b2-4ac) ) / (2a)


"""

import cmath # importing cmath

def quadratic Solution(a,b,c): # Defining function

dis = (b*b)-(4*a*c) # Finding discriminant

if dis < 0: # If discriminant is less than 0, them there are 0 roots

print("Given quadratic equation has no solution.")

elif dis==0: # If discriminant is 0 then there is 1 root

print("Given quadratic equation has one solution:")

print(-b/(2*a))

else: # If discriminant is greater than 0, then there are 2 roots

print("Given Quadratic equation has 2 solutions :")

sol1 = (-b-cmath.sqrt(dis))/(2*a)

sol2 = (-b+cmath.sqrt(dis))/(2*a)

print(sol1, "and", sol2)

# Taking input for a, b and c

a=int(input("Enter value of a:"))

b=int(input("Enter value of b:"))

c=int(input("Enter value of c:"))

# calling function


quadraticSolution(a,b,c)

"""Pregunta 12: Escriba un programa que sirva para evaluar si un estudiante sabe sumar, restar, multiplicar o dividir. Para ello, debe

a. Solicitarle al usuario qué operación desea probar

b. La operación que aparecerá deberá tener dos números aleatorios.

c. El programa definirá si el usuario acertó, o no.

"""

import random
import math

from numpy import mat

# ask operation choice from user
print("Select which operation you want to try-")
print("+ : Add, - : Subtract, * : Multiply, / : Division")
choice = input("Enter your choice: ")

# generate two random numbers between 1 to 50
num1 = random.randint(1, 50)
num2 = random.randint(1, 50)

# ask user from result of operation that he/she select
if(choice == "+"):
    print("What is result of ", num1," + ", num2, ": ")
    answer = int(input())
    # compute original result 
    origianl_result = num1 + num2

    # compare student answer with original result, if both are correct then true
    if(origianl_result == answer):
        print("Your answer is right. Congratulation! You know how to add two numbers.")
    else:
        print("Your answer is wrong. You need more practice for add two numbers.")

elif(choice == "-"):
    print("What is result of ", num1," - ", num2, ": ")
    answer = int(input())
    # compute original result 
    origianl_result = num1 - num2

    # compare student answer with original result, if both are correct then true
    if(origianl_result == answer):
        print("Your answer is right. Congratulation! You know how to subtract two numbers.")
    else:
        print("Your answer is wrong. You need more practice for subtract two numbers.")
    
elif(choice == "*"):
    print("What is result of ", num1," * ", num2, ": ")
    answer = int(input())
    # compute original result 
    origianl_result = num1 * num2

    # compare student answer with original result, if both are correct then true
    if(origianl_result == answer):
        print("Your answer is right. Congratulation! You know how to multiply two numbers.")
    else:
        print("Your answer is wrong. You need more practice for multiply two numbers.")

elif(choice == "/"):
    print("What is result of ", num1," / ", num2, ": ")
    answer = float(input())
    # compute original result 
    origianl_result = num1 / num2

    # compare student answer with original result, if both are correct then true
    if(math.isclose(origianl_result, answer)):
        print("Your answer is right. Congratulation! You know how to divide two numbers.")
    else:
        print("Your answer is wrong. You need more practice for divide two numbers.")
   
else:
    print("Operation you have selected is not available.")

"""Pregunta 13: Realizar programa que permita convertir:

a. cm a metros

b. cm a km

c. metros a km

d. km a cm

e. km a  m.

"""

int main(){
   float centim, meter, kilometer;
   printf("enter length in cm:\n ");
   scanf("%f", &centim);
   meter = centim / 100.0;
   kilometer = centim / 100000.0;
   printf("length in mtrs = %.4f\n", meter);
   printf("length in km = %.4f", kilometer);
   return 0;
}

"""Pregunta 14: Realizar un programa que solicite al usuario que escriba una letra, y defina si es vocal o consonante. El programa no debe funcionar (o indicar que es un error) si se intenta ingresar más de una letra o un número.

"""

letter = input("Please enter a letter: ")

if len(letter) > 1:
print("You can only enter one letter!")
else:
if letter in ['a', 'e', 'i', 'o', 'u']:
print("The letter is a vowel.")
else:
print("The letter is a consonant.")

"""Pregunta 15: Escribir un programa que, dado un número entero, muestre su valor absoluto. 

"""

import math

# Function to find the absolute

# value

def findAbsolute(N):

# Find absolute

X = abs(N);

# Print the absolute value

print(X);

# Driver Code

# Given integer

N = -12;

# Function call

findAbsolute(N);

"""Pregunta 16: Realizar un programa que solicite al usuario que ingrese los nombres de dos usuarios los cuáles se almacenarán en user1 y user2. A continuación, imprimir “coincidencia” si los nombres de ambas personas comienzan con la misma letra o si terminan con la misma letra. Si no es así, imprimir “no hay coincidencia”.

"""

user1=input("Enter the name of user1 : ")
user2=input("Enter the name of user2 : ")
if (user1[0].upper()==user2[0].upper() or user1[-1].upper()==user2[-1].upper()):
    print("match")
else:
    print("not match")

"""Pregunta 17: Escribir un programa que le permita al usuario elegir un candidato por el cual votar: Candidato A por el partido Alfa, Candidato B, por el partido Beta, Candidato C por el partido gamma. Cuando el usuario introduce A, B o C, deberá imprimir por cuál candidato y partido ha votado. Si el usuario introduce otra letra, el programa debe indicarle que ha cometido un error.


"""

print("Enter four grades: ");
grade1=float(input())
grade2=float(input())
grade3=float(input())
grade4=float(input())

sum=grade1+grade2+grade3+grade4
avg=sum/4.0
if(avg>4.5):
print("You are exempt from the last e-x-a-m.")
elif(avg>3.5 and avg<=4.5):
print("You take the e-x-a-m.")
elif(avg>3 and avg<=3.5):
print("You take the e-x-a-m and you must submit a paper")
elif(avg>2 and avg<=3):
print("You must present qualification")
else:
print("you have irretrievably failed the subject")

"""Pregunta 18: Escribir un programa que separe un número en sus unidades, decenas y centenas.

"""

num = int(input('Enter a number: '))


hundreds = (num % 1000) // 100
tens = (num % 100) // 10
units = (num % 10)

print('Units:', units)
print('Tens:', tens)
print('Hundreds:', hundreds)

"""Pregunta 19: Escribir un programa que lea una palabra y defina si es un palíndromo. NOTA: Un palíndromo es una palabra que se lee igual adelante y hacia atrás.

"""

# function to check string is

# palindrome or not

def isPalindrome(str):

# Run loop from 0 to len/2

for i in range(0, int(len(str)/2)):

if str[i] != str[len(str)-i-1]:

return False

return True

# main function

s = "malayalam"

ans = isPalindrome(s)

if (ans):

print("Yes")

else:

print("No")

"""Prregunta 20: Escribir un programa que lea un número y defina si es o no un palíndromo."""

def checkPallindrome(n):
temp=n
rev=0
while(n>0):
dig=n%10
rev=rev*10+dig
n=n//10
if(temp==rev):
return True
else:
return False

n=int(input("Enter Integer: "))
if(checkPallindrome(n)):
print("This number is a palindrome")
else:
print("This number is not palindrome")